### ISSUE TITLE
Drop sudos from npm `scripts`?

### ISSUE THREAD

**Issue by bebraw** [webpack/webpack.io#1]
I noticed the npm scripts run through sudo. I don't think that's needed so might as well drop those bits.

You actually need to change the output path to form `path: 'dist/build',` at `config/dev-config.js` as otherwise it will try to write to root. One reason why sudoing isn't a good idea here.

**Comment by gregvenech** [comment]
Yea definitely should... I updated npm on my macbook and for some reason I'm getting an error when the local installation of Webpack tries to `mkdir`. Just added it as a temporary fix, but I can try to debug the issue I was seeing later tonight.

**Comment by bebraw** [comment]
It was probably that `output.path`. I think you'll find something at your system `/dist/build`. 👍

**Comment by gregvenech** [comment]
@bebraw definitely just found and deleted a `/dist` folder in my system's root 😑
