### ISSUE TITLE
Guide - Concepts - Introduction

### ISSUE THREAD

**Issue by TheLarkInn** [webpack/webpack.io#38]
This will be the either the splash page for the Guide Concepts page. Linkable sections to each "Core Concept". On this page we need to present to users a first time approach to why webpack is needed to solve the common problems with dependencies in web apps. 

* What is a dependency (1-2 sentences)
* What is a dependency to webpack? (2-3 sent. ?)
* What is a dependency tree? (1-2 sent.)
* How does webpack treat the dependencies? (2-3 sent.)
* How does webpack differ from a _module loader_ (IE. SystemJS) (2-3 sent.)
* Why large bundles? (2 sent. ?)

CC @ojacobson

**Comment by TheLarkInn** [comment]
CC @ojacobson for this issue.

**Comment by ojacobson** [comment]
Are we still calling individual nodes in the dependency graph "modules"?

**Comment by TheLarkInn** [comment]
@sokra? I think I can speak for this and say a chunk is "a sub-tree of modules" a module in Webpack is anything you tell webpack to load through loaders ( because webpack treats everything as a module )

**Comment by ojacobson** [comment]
I tried working on the `develop` branch of this repo, but I got hung up fighting with React. So, [here](https://gist.github.com/ojacobson/a33951fc320099564d6393624ac3b1ef)'s a gist with the first draft. I believe this covers the key points; the flow's not great, and I think it needs elaboration in a bunch of places and maybe some narrative, but I wanted to start getting feedback early.

**Comment by TheLarkInn** [comment]
Awesome!!! You can checkout the antwar branch which is in PR I believe. That will land in master here in the next weekish (@bebraw). That should actually work for you. I'll check out the gist right now.

**Comment by TheLarkInn** [comment]
@ojacobson ITS IN MASTER! So feel free and make a real PR if you would like. If you are unsure where to place the .md file @bebraw can guide you.

**Comment by ojacobson** [comment]
Awesome! Unfortunately, [it's not working out for me](https://github.com/webpack/webpack.io/issues/54), so I'll continue on the Gist for now. I did see your comments there; I'll update the gist in place and nudge here.

I did see that @bebraw split this up into more task-specific issues - is there anything I should do there, or is coordinating through here fine for now?

**Comment by ojacobson** [comment]
Gist updated.

**Comment by TheLarkInn** [comment]
Do you have a link to the gist? I couldn't see it from here.

**Comment by ojacobson** [comment]
Whups! I thought the link was already in this thread. [Here you go!](https://gist.github.com/ojacobson/a33951fc320099564d6393624ac3b1ef)

**Comment by TheLarkInn** [comment]
@ojacobson There is a PR I have listed with a few slight changes to the document you provided in the gist. I will get this started in the PR, but welcome any edits or changes.

**Comment by bebraw** [comment]
@TheLarkInn Safe to close given this was merged?

**Comment by TheLarkInn** [comment]
Yup!
