### ISSUE TITLE
Bundle size issue due to unordered plugins

### ISSUE THREAD

**Issue by okbel** [webpack/webpack.io#42]
## **Situation**
People are using Webpack because every React tutorial have Webpack as its module bundler. Some of them are beginners, some others come from Angular with experience in browserify. 
I've seen a lot of beginners struggle with bundle sizes. And even though everything looked fine. Something was off. Some sorting in the plugins array messes up the final size. 
I detected this from people coming from Angular. Since most of angular tutorials/examples don't have webpack in it. Usually they try to extend the default config with the prod config and if the order is not correct, the bundle size incease and you have no clue of what's going on.
I've seen it several times.

## **Issue**
Documentation does not clarify about plugins load order.

## **Solution**
Detailed explanation while handling plugins in Webpack.

**Comment by TheLarkInn** [comment]
Thanks!!!

**Comment by bebraw** [comment]
I'm closing this in favor of #51 ("Concepts - Plugins" article) as that's the perfect place to discuss the topic. Feel free to continue there.
