### ISSUE TITLE
How to - Improve build performance

### ISSUE THREAD

**Issue by mover96** [webpack/webpack.io#46]
[Stub](https://github.com/webpack/webpack.io/blob/develop/content/how-to/improve-build-performance.md).

Here is a great write up on a lot of the features of the DLL Plugin (I cannot figure out how to anchor to specific posts on bountysource, but it's near the bottom)

https://www.bountysource.com/issues/28615391-webpack-incremental-builds-are-slow

The biggest point for me is that it cannot be used with CommonChunksPlugin, but there is a lot of good information in the post as well!

**Disclaimer:** This is my first time submitting to webpack.io, let me know if there are certain conventions I should be following!

**Comment by TheLarkInn** [comment]
We're pretty free form here for right now. Once things get more fleshed out I'm sure we might have a github issue template. But for now: Think of it like an agile user story:

As a user, why do I want this page:


Heres how we answer these questions:

**Comment by bebraw** [comment]
Let's maintain this under [How to improve build performance](https://github.com/webpack/webpack.io/blob/develop/content/how-to/improve-build-performance.md).

**Comment by bebraw** [comment]
I'm closing this in favor of #16 since it's about build performance too. Let's continue there.
