### ISSUE TITLE
Checking location when running the dev server

### ISSUE THREAD

**Issue by gregvenech** [webpack/webpack.io#60]
Opening this for @bebraw 

For the Splash page I'd like to tweak the styling Navigation bar. The cleanest way to do this through React/React-Router is usually to check `props.location` like so:

    let { section, location, config } = props,
          { pathname } = location,
          { home = '/' } = config;
    
    ...
        <Navigation home={ home } pages={ pages } splash={ pathname === '/' } />
    ...

However this always evaluates to false on the dev-server. After some logging it seems that the `pathname` variable is equal to `'/'` when using `npm run build` but when developing always evaluates to `'antwar_devindex'` no matter which page you're on. See the screenshot below:

<img width="427" alt="screen shot 2016-08-01 at 11 42 00 pm" src="https://cloud.githubusercontent.com/assets/8988697/17316415/c5fb53a0-5841-11e6-9ece-25b6dce0871d.png">

Not sure if this is an issue with antwar or our particular setup so I figured I'd create the issue here to start...

**Update:** Just pushed a [new branch](https://github.com/webpack/webpack.io/tree/feature/splash-page) for the Splash page if you want to take a look.

**Comment by bebraw** [comment]
Maybe it would be cleanest to go through the DOM [location API](https://developer.mozilla.org/en-US/docs/Web/API/Location)? That wouldn't tie us to react-router. Maybe we could avoid bundling it to the final build altogether.

**Comment by gregvenech** [comment]
Works for me, I'll use that for now on the splash-page branch.
