### ISSUE TITLE
how to work win windows, laravel/homestead and webpack?¡

### ISSUE THREAD

**Issue by virgenherrera** [webpack/webpack.io#62]
anyone can tellme how to configure this amazing product to work together with virtualbox-vagrant (laravel/homestead)???

i have a project that runs well locally, but when i tryed to run it in vagrant it gives me this error:

vagrant@homestead:~/Code/react$ npm start

> react@1.0.0 start /home/vagrant/Code/react
> webpack-dev-server --content-base app/dist --inline --hot

/home/vagrant/Code/react/node_modules/.bin/webpack-dev-server: 1: /home/vagrant/Code/react/node_modules/.bin/webpack-dev-server: ../webpack-dev-server/bin/webpack-dev-server.js: not found

npm ERR! Linux 4.4.0-22-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v5.12.0
npm ERR! npm  v3.8.6
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! react@1.0.0 start: `webpack-dev-server --content-base app/dist --inline --hot`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the react@1.0.0 start script 'webpack-dev-server --content-base app/dist --inline --hot'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server --content-base app/dist --inline --hot
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/vagrant/Code/react/npm-debug.log

 can anyone helpe????

**Comment by TheLarkInn** [comment]
This is the documentation repository. Issued posted here are for generating documentation on a specific topic.

Please submit an issue on stackoverflow tagged 'webpack' or visit our gitter chat.

However in the future if you learn how to do this and want to share the wonderful amazing joys of using webpack with laravel and friends, please feel free to contribute to our documentation. You will be rewarded with countless metaphorical thumbs up and pats on the back for your time and sacrifice.
