### ISSUE TITLE
[Styling]: Need to use Monospaced font for code blocks.

### ISSUE THREAD

**Issue by TheLarkInn** [webpack/webpack.io#74]
Currently code blocks are looking a bit lacking and harder to read because the typeface that is being used is not monospaced. Therefore, things to not appear to be lined up. Seen below is an example. 

<img width="1534" alt="screen shot 2016-08-23 at 9 50 11 pm" src="https://cloud.githubusercontent.com/assets/3408176/17916732/a5a8b34a-697b-11e6-9445-99c8f80635f2.png">

**Comment by gregvenech** [comment]
Sorry completely blanked on this when I was refactoring the css, just pushed 5a2e228d657681624c04a4bae4586cc96fd8b4ea which contains the fix.
