### ISSUE TITLE
Figure out how to migrate documentation issues from the main repo to here

### ISSUE THREAD

**Issue by bebraw** [webpack/webpack.io#82]
Issues: https://github.com/webpack/webpack/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-asc+label%3Adocumentation .

Ideally comments should be retained. Labels can be lost.

**Comment by bebraw** [comment]
Reference by @danez:

* https://gist.github.com/jonmagic/5282384165e0f86ef105
* https://github.com/babel/phabricator-to-github/blob/master/src/github/api/importIssue.js

**Comment by danez** [comment]
The only advantage of this new API is that there are no notifications triggered, and comments/issues will be dated like the real ones. If that is not a requirement, then the normal issue API might be better, as there are tools and libraries implementing it.

**Comment by bebraw** [comment]
Given there are about sixty issues to move, a little notification storm doesn't hurt. Losing dates isn't a problem, but it would nice to retain the threads.

**Comment by pksjce** [comment]
#98 is something I was able to create with [https://github-issue-mover.appspot.com/](https://github-issue-mover.appspot.com/) . Is that something that you expected?
It also adds a comment and ref to the original issue [#1330](https://github.com/webpack/webpack/issues/1330)

**Comment by bebraw** [comment]
Completed. Thanks @pksjce.
