### ISSUE TITLE
Run ESLint against the code examples

### ISSUE THREAD

**Issue by bebraw** [webpack/webpack.io#92]
1. Glob all Markdown files.
2. Hook into marked lexer and extract code fragments. [Example](https://github.com/webpack/webpack.io/blob/develop/utilities/markdown.js).
3. Eliminate any custom markup (i.e., ellipsis).
4. Run eslint against the code fragments.

**Comment by bebraw** [comment]
It's likely best to adapt [eslint-plugin-markdown](https://github.com/eslint/eslint-plugin-markdown) for this purpose by the looks of it.

**Comment by TheLarkInn** [comment]
<img width="913" alt="screen shot 2016-09-06 at 12 24 39 am" src="https://cloud.githubusercontent.com/assets/3408176/18262567/6e853fee-73c8-11e6-85e7-128a1d67a416.png">
Looks like I was able to get it to run. Pretty slick.

**Comment by TheLarkInn** [comment]
I'm going to PR this. Pretty minor.
